// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.gttn.mapmodule.domain;

import com.gttn.mapmodule.domain.Mapmodule;

privileged aspect Mapmodule_Roo_JavaBean {
    
    public String Mapmodule.getName() {
        return this.name;
    }
    
    public void Mapmodule.setName(String name) {
        this.name = name;
    }
    
}
